### ISSUE TITLE
Double softmax in OOD score computation of stamp

### ISSUE THREAD

**Issue by MarcLafon** [yuyongcan/STAMP#2]
It seems that the ood score used in stamp is obtained via a double softmax operation. The outupt of the forward function of stamp is already a probability vector as it is computed with the softmax operator (lines 184-189 of the stamp.py file). Then the ood score in the get_accuracy function in the utils.py file is again computed using the softmax_entropy function (line 256).

**Comment by yuyongcan** [comment]
Thanks for your correction. We fixed the bug in our latest version.
