### ISSUE TITLE
Environment Setting Issuse

### ISSUE THREAD

**Issue by Chinafsh** [yuyongcan/STAMP#3]
thx for u brilliant work. I got a problem about environment.

ERROR: Could not find a version that satisfies the requirement matpotlib==0.0.1 (from versions: none)
ERROR: No matching distribution found for matpotlib==0.0.1

Could u help me. Thx.

**Comment by Chinafsh** [comment]
> thx for u brilliant work. I got a problem about environment.
> 
> ERROR: Could not find a version that satisfies the requirement matpotlib==0.0.1 (from versions: none) ERROR: No matching distribution found for matpotlib==0.0.1
> 
> Could u help me. Thx.

@yuyongcan Plz!!!!!!

**Comment by yuyongcan** [comment]
> thx for u brilliant work. I got a problem about environment.
> 
> ERROR: Could not find a version that satisfies the requirement matpotlib==0.0.1 (from versions: none) ERROR: No matching distribution found for matpotlib==0.0.1
> 
> Could u help me. Thx.

You can ignore this library. Remove it from the environment.yaml

**Comment by Chinafsh** [comment]
> > thx for u brilliant work. I got a problem about environment.
> > ERROR: Could not find a version that satisfies the requirement matpotlib==0.0.1 (from versions: none) ERROR: No matching distribution found for matpotlib==0.0.1
> > Could u help me. Thx.
> 
> You can ignore this library. Remove it from the environment.yaml

I see. thx.
